FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/skillforge1-c6433/firestore/indexes?create_composite=ClJwcm9qZWN0cy9za2lsbGZvcmdlMS1jNjQzMy9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvY29udGVudHMvaW5kZXhlcy9fEAEaEAoMdXBsb2FkZXJfdWlkEAEaDgoKY3JlYXRlZF9hdBACGgwKCF9fbmFtZV9fEAI