create policy "Users can view their own profile"
on "public"."profiles"

as PERMISSIVE

for SELECT

to authenticated

using (

7
auth.uid() = user_id

);

Error running SQL query

Hide error details
ERROR:  operator does not exist: uuid = bigint
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.